### ISSUE TITLE
#50.6 build failed

### ISSUE THREAD

**Issue by RazeSoldier** [RazeSoldier/PhpWget#1]
[This build](https://travis-ci.org/RazeSoldier/PhpWget/jobs/325699114) is failed.

`PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'phar error: "/home/travis/build/RazeSoldier/PhpWget/tests/tar.v0.1" is a corrupted tar file (checksum mismatch of file "52 comment=51cda411beada7b186aa154fde84cb182d73677d
")' in /home/travis/build/RazeSoldier/PhpWget/phpwget.php:406
Stack trace:
#0 /home/travis/build/RazeSoldier/PhpWget/phpwget.php(406): PharData->__construct('tar.v0.1')
#1 /home/travis/build/RazeSoldier/PhpWget/phpwget.php(299): PhpWget\unzip->unZip()
#2 /home/travis/build/RazeSoldier/PhpWget/phpwget.php(414): PhpWget\downloadFile->download()
#3 {main}
  thrown in /home/travis/build/RazeSoldier/PhpWget/phpwget.php on line 406`

**Comment by RazeSoldier** [comment]
Due to [Bug #64343](https://bugs.php.net/bug.php?id=64343), PHP 5.5.24- version can't extract BSD generated tar file, only support `ustar` format.
